<?php

use Illuminate\Support\Facades\Storage;
use Livewire\Attributes\Computed;
use Livewire\Attributes\On;
use Livewire\Attributes\Url;
use Livewire\Component;
use Livewire\WithFileUploads;
use Noerd\Cms\Helpers\CollectionHelper;
use Noerd\Cms\Helpers\FieldHelper;
use Noerd\Cms\Models\CmsLanguage;
use Noerd\Cms\Models\Collection;
use Noerd\Cms\Models\ElementPage;
use Noerd\Cms\Models\Page;
use Noerd\Cms\Services\FieldTypeConverter;
use Noerd\Media\Models\Media;
use Noerd\Media\Services\MediaUploadService;
use Noerd\Traits\NoerdDetail;

new class extends Component
{
    use NoerdDetail;
    use WithFileUploads;

    #[Url(as: 'pageId', keep: false, except: '')]
    public $modelId = null;

    public const DETAIL_CLASS = Page::class;

    public const DETAIL_COMPONENT = 'page-detail';

    public ?array $collectionLayout = null;

    public ?string $collectionKey = null;

    public array $collectionData = [];

    public array $images = [];

    public string $hrefPage = '';

    public bool $slugAutoGenerated = false;

    public $lastChangeTime;

    #[Computed]
    public function hasPageFeatures(): bool
    {
        if (! $this->collectionKey || ! $this->collectionLayout) {
            return true;
        }

        return $this->collectionLayout['hasPage'] ?? true;
    }

    #[Computed]
    public function pageModel(): ?Page
    {
        if (! $this->modelId) {
            return null;
        }

        return Page::with('elements')->find($this->modelId);
    }

    #[Computed]
    public function elements()
    {
        return FieldHelper::getAllElements();
    }

    public function mount(?string $collectionKey = null): void
    {
        $this->initDetail();

        $this->collectionKey = $collectionKey ?? $this->collectionKey;

        if ($this->collectionKey) {
            $this->collectionLayout = CollectionHelper::getCollectionFields($this->collectionKey);
        }

        $page = new Page;
        if ($this->modelId) {
            $page = Page::find($this->modelId) ?? new Page;
        }

        $this->mountPageDetail($page);

        // For collection entries: Merge data from the data column into detailData for proper wire:model binding
        if ($this->collectionKey && isset($this->detailData['data']) && is_array($this->detailData['data'])) {
            $this->collectionData = $this->detailData['data'];
            foreach ($this->detailData['data'] as $key => $value) {
                if (! str_starts_with($key, 'detailData.') && ! in_array($key, ['name', 'slug', 'layout', 'sort'], true)) {
                    $this->detailData[$key] = $value;
                }
            }
        }

        // Ensure sort field is available for collections
        $this->detailData['sort'] ??= $page->sort ?? 0;
    }

    protected function mountPageDetail(?Page $page = null): void
    {
        if (! $page) {
            $page = new Page;
        }

        $this->detailData = $page->toArray();

        $availableLayouts = $this->layoutOptions();
        if (! isset($this->detailData['layout']) || empty($this->detailData['layout'])) {
            $this->detailData['layout'] = array_key_first($availableLayouts);
        }

        $activeLangCodes = $this->getActiveTenantLanguageCodes();
        if (empty($activeLangCodes)) {
            $activeLangCodes = [$this->getDefaultLanguageCode()];
        }

        if (isset($this->detailData['slug'])) {
            if (! is_array($this->detailData['slug']) || empty($this->detailData['slug'])) {
                $this->detailData['slug'] = $this->initializeEmptySlugArray();
            } else {
                foreach ($activeLangCodes as $lang) {
                    if (! isset($this->detailData['slug'][$lang]) || ! is_string($this->detailData['slug'][$lang])) {
                        $this->detailData['slug'][$lang] = '';
                    }
                }
            }
        } else {
            $this->detailData['slug'] = $this->initializeEmptySlugArray();
        }

        $this->detailData['additional_fields'] = $this->detailData['additional_fields'] ?? [];

        $this->lastChangeTime = time();
        $this->slugAutoGenerated = false;
    }

    public function layoutOptions(): array
    {
        $layoutsDirectory = base_path('app-modules/website/resources/views/components/layouts');
        $options = [];

        if (is_dir($layoutsDirectory)) {
            foreach (glob($layoutsDirectory.'/*.blade.php') as $filePath) {
                $fileName = basename($filePath, '.blade.php');

                if (str_starts_with($fileName, '_')) {
                    continue;
                }

                $options[$fileName] = $fileName;
            }
        }

        if (empty($options)) {
            $options['weblayout'] = 'weblayout';
        }

        return $options;
    }

    public function getDefaultLanguageCode(): string
    {
        $defaultLanguage = CmsLanguage::where('tenant_id', auth()->user()->selected_tenant_id)
            ->where('is_default', true)
            ->first();

        return $defaultLanguage?->code ?? 'en';
    }

    public function getActiveTenantLanguageCodes(): array
    {
        return CmsLanguage::where('tenant_id', auth()->user()->selected_tenant_id)
            ->where('is_active', true)
            ->orderBy('is_default', 'desc')
            ->pluck('code')
            ->toArray();
    }

    public function generateSlug(string $name, ?string $languageCode = null): string
    {
        $slug = str_replace(['ä', 'ö', 'ü', 'ß', 'Ä', 'Ö', 'Ü'], ['ae', 'oe', 'ue', 'ss', 'ae', 'oe', 'ue'], $name);
        $slug = mb_strtolower($slug);
        $slug = preg_replace('/[^a-z0-9\s-]/', '', $slug);
        $slug = preg_replace('/[\s-]+/', '-', $slug);
        $slug = mb_trim($slug, '-');

        if ($languageCode && $languageCode !== $this->getDefaultLanguageCode()) {
            $slug = $languageCode.'/'.$slug;
        }

        return '/'.$slug;
    }

    public function updated($propertyName, $value): void
    {
        if (! str_starts_with($propertyName, 'detailData.name.')) {
            return;
        }

        $language = str_replace('detailData.name.', '', $propertyName);

        if (! empty($value)) {
            if (! isset($this->detailData['slug']) || ! is_array($this->detailData['slug'])) {
                $this->detailData['slug'] = $this->initializeEmptySlugArray();
            }

            if (empty($this->detailData['slug'][$language] ?? '')) {
                $generatedSlug = $this->generateSlug($value, $language);
                $this->detailData['slug'][$language] = $generatedSlug;
            }
        }
    }

    public function updatedImages(): void
    {
        $mediaUploadService = app()->make(MediaUploadService::class);
        foreach ($this->images as $key => $image) {
            $media = $mediaUploadService->storeFromUploadedFile($image);
            $this->detailData[$key] = $this->urlWithoutDomain($media);
        }
    }

    public function deleteImage(string $fieldName): void
    {
        $this->detailData[$fieldName] = null;
    }

    public function openSelectMediaModal(string $fieldName): void
    {
        $token = uniqid('media_', true);
        $this->detailData['__mediaToken'] = $token;
        $this->dispatch(
            event: 'noerdModal',
            modalComponent: 'media-list',
            arguments: ['selectMode' => true, 'selectContext' => $fieldName, 'selectToken' => $token],
        );
    }

    #[On('mediaSelected')]
    public function mediaSelected(int $mediaId, ?string $fieldName = 'image', ?string $token = null): void
    {
        if (($this->detailData['__mediaToken'] ?? null) !== $token) {
            return;
        }
        $media = Media::find($mediaId);
        if (! $media) {
            return;
        }
        $this->detailData[$fieldName ?? 'image'] = $this->urlWithoutDomain($media);
        unset($this->detailData['__mediaToken']);
    }

    #[On('elementPicked')]
    public function addElement($elementKey): void
    {
        $sortElement = ElementPage::where('page_id', $this->modelId)
            ->orderBy('sort', 'desc')
            ->first();

        ElementPage::create([
            'page_id' => $this->modelId,
            'element_key' => $elementKey,
            'sort' => ($sortElement?->sort ?? 0) + 1,
            'data' => '{}',
        ]);

        $this->lastChangeTime = time();
    }

    #[On('pageSelected')]
    public function pageSelected($value, $context): void
    {
        $page = Page::find($value);
        $this->hrefPage = $page['name'][session('selectedLanguage')];
        $this->relationTitles[$value] = $page['name'][session('selectedLanguage')];
        $this->detailData[str_replace('detailData.', '', $context)] = $page->id;
    }

    public function elementSort($elementId, $newPosition): void
    {
        $elements = ElementPage::where('page_id', $this->modelId)
            ->orderBy('sort')
            ->get();
        $loop = 0;
        foreach ($elements as $element) {
            if ($newPosition === $loop) {
                $loop++;
            }
            if ($element['id'] === $elementId) {
                $element->sort = $newPosition;
                $element->save();
            } else {
                $element->sort = $loop++;
                $element->save();
            }
        }
        $this->lastChangeTime = time();
    }

    public function deleteElement(int $elementPageId): void
    {
        $element = ElementPage::find($elementPageId);
        if ($element && (int) $element->page_id === (int) $this->modelId) {
            $element->delete();
            $this->lastChangeTime = time();
            $this->dispatch('reloadPageComponent');
        }
    }

    #[On('reloadPageComponent')]
    public function reloadPage(): void
    {
        $this->lastChangeTime = time();
    }

    #[On('languageChanged')]
    public function refresh(): void
    {
        $this->dispatch('$refresh');
    }

    public function openElements(): void
    {
        $this->dispatch(
            event: 'noerdModal',
            modalComponent: 'element-page-detail',
            source: $this->getComponentName(),
            arguments: ['elementPageId' => $this->modelId],
        );
    }

    public function getPageUrl(): ?string
    {
        $selectedLanguage = session('selectedLanguage') ?? $this->getDefaultLanguageCode();
        $slug = $this->detailData['slug'][$selectedLanguage] ?? null;

        if (! $slug) {
            return null;
        }

        return url($slug);
    }

    public function store(): void
    {
        if ($this->collectionKey) {
            $this->storeCollectionPage();

            return;
        }

        $this->validate([
            'detailData.name' => ['required', 'array', 'max:255'],
            'detailData.slug' => ['required', 'array'],
        ]);

        if (! empty($validationErrors)) {
            $this->addError('detailData.slug', reset($validationErrors));

            return;
        }

        $data = $this->detailData;
        $data['tenant_id'] = auth()->user()->selected_tenant_id;

        if (empty($data['layout'])) {
            $data['layout'] = array_key_first($this->layoutOptions());
        }

        $cleanSlugData = [];
        if (isset($this->detailData['slug']) && is_array($this->detailData['slug'])) {
            foreach ($this->detailData['slug'] as $lang => $slug) {
                if (! empty($slug)) {
                    $cleanSlugData[$lang] = $slug;
                }
            }
        }

        $data['slug'] = $cleanSlugData;
        $data['name'] = $this->detailData['name'];

        $page = Page::updateOrCreate(
            ['id' => $this->modelId],
            $data,
        );

        $this->dispatch('storeElements');

        $this->storeProcess($page);
    }

    public function delete(): void
    {
        $page = Page::find($this->modelId);
        $page->delete();
        $this->closeModalProcess($this->getListComponent());
    }

    /**
     * Get collection field names from the YAML definition (without detailData. prefix).
     */
    private function getCollectionFieldNames(): array
    {
        if (! $this->collectionLayout || ! isset($this->collectionLayout['fields'])) {
            return [];
        }

        $fieldNames = [];
        foreach ($this->collectionLayout['fields'] as $field) {
            $name = $field['name'] ?? '';
            $name = str_replace(['detailData.', 'model.'], '', $name);
            if (! empty($name)) {
                $fieldNames[] = $name;
            }
        }

        return $fieldNames;
    }

    /**
     * Extract only collection-specific fields from detailData.
     */
    private function extractCollectionData(): array
    {
        $collectionFieldNames = $this->getCollectionFieldNames();
        $collectionData = [];

        foreach ($collectionFieldNames as $fieldName) {
            if (array_key_exists($fieldName, $this->detailData)) {
                $collectionData[$fieldName] = $this->detailData[$fieldName];
            }
        }

        return $collectionData;
    }

    private function storeCollectionPage(): void
    {
        $parentCollection = Collection::firstOrCreate([
            'tenant_id' => auth()->user()->selected_tenant_id,
            'collection_key' => mb_strtoupper($this->collectionKey),
        ], [
            'name' => ucfirst($this->collectionKey),
        ]);

        $hasPageFeatures = $this->collectionLayout['hasPage'] ?? true;

        $rawCollectionData = $this->extractCollectionData();
        $convertedCollectionData = FieldTypeConverter::convertCollectionData($rawCollectionData, $this->collectionKey);

        $data = [
            'tenant_id' => auth()->user()->selected_tenant_id,
            'collection_id' => $parentCollection->id,
            'data' => $convertedCollectionData,
            'sort' => (int) ($this->detailData['sort'] ?? 0),
        ];

        $availableLayouts = $this->layoutOptions();
        $data['layout'] = $this->detailData['layout'] ?? array_key_first($availableLayouts);

        if ($hasPageFeatures) {
            $nameData = [];
            if (isset($this->detailData['name']) && is_array($this->detailData['name'])) {
                foreach ($this->detailData['name'] as $lang => $nameValue) {
                    if (! empty($nameValue)) {
                        $nameData[$lang] = $nameValue;
                    }
                }
            }

            $slugData = [];
            if (isset($this->detailData['slug']) && is_array($this->detailData['slug'])) {
                foreach ($this->detailData['slug'] as $lang => $slug) {
                    if (! empty($slug)) {
                        $slugData[$lang] = $slug;
                    } elseif (! empty($nameData[$lang] ?? '')) {
                        $slugData[$lang] = $this->generateSlug($nameData[$lang], $lang);
                    }
                }
            }

            if (empty($nameData)) {
                $defaultLang = $this->getDefaultLanguageCode();
                $nameData[$defaultLang] = 'Collection Page';
                $slugData[$defaultLang] = '/collection-page';
            }

            $data['name'] = $nameData;
            $data['slug'] = $slugData;
            $data['is_active'] = true;
        } else {
            $data['name'] = null;
            $data['slug'] = null;
            $data['is_active'] = true;
        }

        $page = Page::updateOrCreate(['id' => $this->modelId], $data);

        $this->storeProcess($page);

        $this->dispatch('storeElements');
    }

    private function initializeEmptySlugArray(): array
    {
        $languages = $this->getActiveTenantLanguageCodes();
        if (empty($languages)) {
            $languages = [$this->getDefaultLanguageCode()];
        }

        return array_fill_keys($languages, '');
    }

    private function urlWithoutDomain(Media $media): string
    {
        $url = Storage::disk($media->disk)->url($media->path);

        return mb_strstr($url, '/storage');
    }
} ?>

<x-noerd::page :disableModal="$disableModal">

    <x-slot:header>
        <x-noerd::modal-title class="flex items-center">
            {{ $collectionLayout['title'] ?? __('Page') }}

            <div class="ml-auto" :class="isModal ? 'mr-22' : ''">
                <div class="flex items-center gap-4">
                    <livewire:language-switcher/>

                    @if($this->pageModel?->id && $this->hasPageFeatures)
                        @php $pageUrl = $this->getPageUrl(); @endphp
                        @if($pageUrl)
                            <a href="{{ $pageUrl }}" target="_blank"
                               class="px-4 py-2 rounded-md text-sm font-medium bg-gray-900 text-white hover:bg-gray-800 transition-colors">
                                {{ __('Zur Seite') }}
                            </a>
                        @endif
                    @endif
                </div>
            </div>

        </x-noerd::modal-title>
    </x-slot:header>
    <div>
        @if($collectionLayout)
            <!-- Sort Field for Collections -->
            <div class="flex">
                <div class="flex ml-auto items-center my-6 space-x-4">
                    <div class="flex ml-auto items-center space-x-2">
                        <label for="sort" class="text-sm text-gray-600 font-medium">Sort:</label>
                        <input
                            wire:model="detailData.sort"
                            id="sort"
                            type="number"
                            min="0"
                            step="1"
                            class="w-16 rounded-md border border-zinc-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-accent focus:border-transparent"
                        />
                    </div>
                </div>
            </div>

            <!-- Collection Fields (Blue Box) -->
            <div class="p-4 border border-blue-200 mb-4 relative overflow-hidden rounded-lg bg-blue-50 after:pointer-events-none after:absolute after:inset-0 after:rounded-lg after:inset-ring after:inset-ring-blue-950/5 bg-[image:radial-gradient(var(--pattern-fg)_1px,_transparent_0)] bg-[size:10px_10px] bg-fixed [--pattern-fg:var(--color-blue-950)]/5">
                @include('noerd::components.detail.block', array_merge($collectionLayout, ['model' => $detailData]))
            </div>
        @endif

        <x-noerd::tab-content :layout="$pageLayout" :showBlock="$this->hasPageFeatures" :model="$detailData">
            <x-slot:tab1>
                @include('cms::components._page-elements', ['hasPageFeatures' => $this->hasPageFeatures])
            </x-slot:tab1>
        </x-noerd::tab-content>
    </div>

    <x-slot:footer>
        <x-noerd::delete-save-bar :showDelete="isset($modelId)"/>
    </x-slot:footer>

</x-noerd::page>
