<?php

use Livewire\Attributes\Computed;
use Livewire\Attributes\On;
use Livewire\Attributes\Url;
use Livewire\Volt\Component;
use Livewire\Volt\Volt;
use Noerd\Cms\Helpers\FieldHelper;
use Noerd\Cms\Models\Collection;
use Noerd\Cms\Models\ElementPage;
use Noerd\Cms\Models\Language;
use Noerd\Cms\Models\Page;
use Noerd\Website\Services\PageElementService;
use Noerd\Noerd\Traits\Noerd;

new class extends Component {

    use Noerd;

    public const COMPONENT = 'page-component';
    public const LIST_COMPONENT = 'pages-table';
    public const ID = 'pageId';
    #[Url(keep: false, except: '')]
    public $pageId = null;

    public array $model;
    public Page $page;
    public bool $slugAutoGenerated = false;
    public string $viewMode = 'content'; // 'content' or 'preview'

    #[Computed]
    public function elements()
    {
        return FieldHelper::getAllElements();
    }

    #[Computed]
    public function previewElements()
    {
        if (!$this->page->id) {
            return [];
        }

        $pageElementService = app(PageElementService::class);
        $selectedLanguage = session('selectedLanguage', 'de');

        return $pageElementService->processPageElements($this->page, $selectedLanguage);
    }

    #[Computed]
    public function availableCollections()
    {
        return Collection::where('tenant_id', auth()->user()->selected_tenant_id)
            ->orderBy('name')
            ->get();
    }

    #[Computed]
    public function pageCollections()
    {
        if (!$this->page->id) {
            return collect();
        }

        return $this->page->collections()->get();
    }

    public array $liveElementData = [];
    public int $previewTick = 0;
    
    // Collections
    public array $selectedCollectionIds = [];
    public bool $showCollectionModal = false;

    #[Computed]
    public function livePreviewElements()
    {
        if (!$this->page->id) {
            return [];
        }

        try {
            // Get the base elements from database
            $pageElementService = app(PageElementService::class);
            $selectedLanguage = session('selectedLanguage', 'de');
            $elements = $pageElementService->processPageElements($this->page, $selectedLanguage);

            // Merge with live element data from form inputs
            foreach ($elements as $index => $element) {
                $elementPageId = $element['id'] ?? ($this->page->elements[$index]->id ?? null);
                if ($elementPageId && isset($this->liveElementData[$elementPageId])) {
                    // Ensure both are arrays before merging
                    $baseData = is_array($element['data'] ?? []) ? ($element['data'] ?? []) : [];
                    $liveData = is_array($this->liveElementData[$elementPageId]) ? $this->liveElementData[$elementPageId] : [];

                    // Process live data to ensure proper localization format
                    $processedLiveData = [];
                    foreach ($liveData as $key => $value) {
                        // If the value is already localized (array with language keys), keep it
                        if (is_array($value) && isset($value[$selectedLanguage])) {
                            $processedLiveData[$key] = $value[$selectedLanguage];
                        } elseif (is_array($value)) {
                            // If it's an array but not localized, try to get the first value or convert to string
                            $processedLiveData[$key] = is_string(reset($value)) ? reset($value) : json_encode($value);
                        } else {
                            // If it's already a string or simple value, use it directly
                            $processedLiveData[$key] = $value;
                        }
                    }

                    $elements[$index]['data'] = array_merge($baseData, $processedLiveData);
                }
            }

            return $elements;
        } catch (\Exception $e) {
            // Fallback to regular preview elements if something goes wrong
            \Log::error('Error in livePreviewElements: ' . $e->getMessage());
            return $this->previewElements;
        }
    }

    #[On('updateLiveElementData')]
    public function updateLiveElementData($elementPageId, $data)
    {
        $this->liveElementData[$elementPageId] = $data;
        // Bump preview tick to force remount of preview child components only
        $this->previewTick++;
    }

    #[Computed]
    public function componentMapping()
    {
        $pageElementService = app(PageElementService::class);
        return $pageElementService->getComponentMapping();
    }

    public function mount(Page $model): void
    {
        if ($this->modelId) {
            $model = Page::find($this->modelId);
        }

        $this->page = $model;
        $this->mountModalProcess(self::COMPONENT, $model);

        // Special case for Page/Element fields
        $this->model = FieldHelper::parseComponentToData('page-component', $model->toArray());

        // Fix slug field if it's malformed or shows [object Object]
        if (isset($this->model['slug'])) {
            // If slug is not an array or is malformed, reset it
            if (!is_array($this->model['slug']) || empty($this->model['slug'])) {
                $this->model['slug'] = ['de' => '', 'en' => ''];
            } else {
                // Ensure each language has a string value
                foreach (['de', 'en'] as $lang) {
                    if (!isset($this->model['slug'][$lang]) || !is_string($this->model['slug'][$lang])) {
                        $this->model['slug'][$lang] = '';
                    }
                }
            }
        } else {
            // Initialize empty slug array if not exists
            $this->model['slug'] = ['de' => '', 'en' => ''];
        }

        $this->lastChangeTime = time();

        // Load selected collections
        if ($this->page->id) {
            $this->selectedCollectionIds = $this->page->collections()->pluck('collections.id')->toArray();
        }

        // Initialize slugAutoGenerated flag
        // This is mainly used for preventing automatic updates of existing slugs
        // but we still allow generation for new languages
        $this->slugAutoGenerated = false;
    }

    public function getDefaultLanguageCode(): string
    {
        $defaultLanguage = Language::where('tenant_id', auth()->user()->selected_tenant_id)
            ->where('is_default', true)
            ->first();

        return $defaultLanguage ? $defaultLanguage->code : 'de';
    }

    public function generateSlug(string $name, string $languageCode = null): string
    {
        // Replace umlauts and special characters BEFORE lowercasing
        $slug = str_replace(['ä', 'ö', 'ü', 'ß', 'Ä', 'Ö', 'Ü'], ['ae', 'oe', 'ue', 'ss', 'ae', 'oe', 'ue'], $name);

        // Convert to lowercase
        $slug = strtolower($slug);

        // Remove all non-alphanumeric characters and spaces, replace with hyphens
        $slug = preg_replace('/[^a-z0-9\s-]/', '', $slug);

        // Replace multiple spaces/hyphens with single hyphen
        $slug = preg_replace('/[\s-]+/', '-', $slug);

        // Trim hyphens from beginning and end
        $slug = trim($slug, '-');

        // Add language prefix if not default language
        if ($languageCode && $languageCode !== $this->getDefaultLanguageCode()) {
            $slug = $languageCode . '/' . $slug;
        }

        // Ensure slug starts with forward slash
        return '/' . $slug;
    }

    public function updated($propertyName, $value): void
    {
        // Only handle name field updates
        if (!str_starts_with($propertyName, 'model.name.')) {
            return;
        }

        // Extract language from property name (e.g., 'model.name.de' -> 'de')
        $language = str_replace('model.name.', '', $propertyName);

        // Auto-generate slug if name has content and slug is empty for this language
        if (!empty($value)) {
            // Ensure slug array exists
            if (!isset($this->model['slug']) || !is_array($this->model['slug'])) {
                $this->model['slug'] = ['de' => '', 'en' => ''];
            }

            // Only generate slug if this specific language doesn't have a slug yet
            if (empty($this->model['slug'][$language] ?? '')) {
                $generatedSlug = $this->generateSlug($value, $language);
                $this->model['slug'][$language] = $generatedSlug;
            }
        }
    }

    public function store(): void
    {
        $this->validate([
            'model.name' => ['required', 'array', 'max:255'],
            'model.slug' => ['required', 'array'],
        ]);

        // Custom validation for slug format and uniqueness
        $validationErrors = [];
        if (isset($this->model['slug']) && is_array($this->model['slug'])) {
            foreach ($this->model['slug'] as $lang => $slug) {
                // Only validate slug if there's a corresponding name for this language
                if (!isset($this->model['name'][$lang]) || empty($this->model['name'][$lang])) {
                    continue;
                }

                if (empty($slug)) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} ist erforderlich.";
                    continue;
                }

                // Check if slug is string
                if (!is_string($slug)) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} muss ein Text sein.";
                    continue;
                }

                // Check if slug starts with forward slash
                if (!str_starts_with($slug, '/')) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} muss mit einem '/' beginnen.";
                    continue;
                }

                // Check slug format (only lowercase letters, numbers, hyphens, slashes, and forward slash at start)
                // Allow format: /slug or /lang/slug (where lang is 2-3 characters)
                if (!preg_match('/^\/([a-z]{2,3}\/)?[a-z0-9-]+$/', $slug)) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} darf nur Kleinbuchstaben, Zahlen, Bindestriche und optional einen Sprachprefix enthalten und muss mit '/' beginnen.";
                    continue;
                }

                // Check for duplicate slugs in database (excluding current record)
                $existingPage = \Noerd\Cms\Models\Page::where('tenant_id', auth()->user()->selected_tenant_id)
                    ->where('id', '!=', $this->modelId)
                    ->whereRaw("JSON_EXTRACT(slug, '$.{$lang}') = ?", [$slug])
                    ->first();

                if ($existingPage) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug '{$slug}' für Sprache {$lang} wird bereits verwendet.";
                }
            }
        }

        if (!empty($validationErrors)) {
            $this->addError('model.slug', reset($validationErrors));
            return;
        }

        $model = $this->model;
        $model['tenant_id'] = auth()->user()->selected_tenant_id;

        // Clean up slug data before saving - remove empty values
        $cleanSlugData = [];
        if (isset($this->model['slug']) && is_array($this->model['slug'])) {
            foreach ($this->model['slug'] as $lang => $slug) {
                if (!empty($slug)) {
                    $cleanSlugData[$lang] = $slug;
                }
            }
        }

        // TODO auto detect if value is an array and convert it to JSON
        $model['slug'] = json_encode($cleanSlugData);
        $model['name'] = json_encode($this->model['name']);


        $page = Page::updateOrCreate(['id' => $this->modelId],
            $model);

        // Sync collections
        $this->syncCollections($page);

        $this->dispatch('storeElements');
        $this->showSuccessIndicator = true;

        if ($page->wasRecentlyCreated) {
            $this->modelId = $page['id'];
            $this->page = $page;
        }
    }

    public function delete(): void
    {
        $page = Page::find($this->modelId);
        $page->delete();
        $this->closeModalProcess(self::LIST_COMPONENT);
    }

    public function addElement($elementKey)
    {
        $sortElement = ElementPage::where('page_id', $this->modelId)
            ->orderBy('sort', 'desc')
            ->first();

        ElementPage::create([
            'page_id' => $this->modelId,
            'element_key' => $elementKey,
            'sort' => ($sortElement?->sort ?? 0) + 1,
            'data' => '{}',
        ]);

        $this->lastChangeTime = time();
    }

    public function insertElementAt(int $position, string $elementKey): void
    {
        $elements = ElementPage::where('page_id', $this->modelId)
            ->orderBy('sort')
            ->get();

        // Clamp position
        $position = max(0, min($position, $elements->count()));

        // Shift elements at and after position by +1
        foreach ($elements as $index => $element) {
            if ($index >= $position) {
                $element->sort = $element->sort + 1;
                $element->save();
            }
        }

        // Insert new element at position with expected sort
        $newSort = ($elements[$position - 1]->sort ?? -1) + 1;
        ElementPage::create([
            'page_id' => $this->modelId,
            'element_key' => $elementKey,
            'sort' => $newSort,
            'data' => '{}',
        ]);

        $this->lastChangeTime = time();
        $this->dispatch('reloadPageComponent');
    }

    public function elementSort($elementId, $newPosition): void
    {
        $elements = ElementPage::where('page_id', $this->modelId)
            ->orderBy('sort')
            ->get();
        $loop = 0;
        foreach ($elements as $element) {
            if ($newPosition === $loop) {
                $loop++;
            }
            if ($element['id'] === $elementId) {
                $element->sort = $newPosition;
                $element->save();
            } else {
                $element->sort = $loop++;
                $element->save();
            }
        }
        $this->lastChangeTime = time();
    }

    public function deleteElement(int $elementPageId): void
    {
        $element = ElementPage::find($elementPageId);
        if ($element && (int)$element->page_id === (int)$this->modelId) {
            $element->delete();
            $this->lastChangeTime = time();
            $this->dispatch('reloadPageComponent');
        }
    }

    #[On('reloadPageComponent')]
    public function reloadPage()
    {
        $this->lastChangeTime = time();
    }

    #[On('languageChanged')]
    public function refresh()
    {
        $this->dispatch('$refresh');
    }

    public function openElements()
    {
        $this->dispatch(
            event: 'noerdModal',
            component: 'element-page-component',
            source: self::COMPONENT,
            arguments: ['modelId' => $this->pageId],
        );
    }

    #[On('elementPicked')]
    public function onElementPicked(string $elementKey, ?string $token = null): void
    {
        // Determine insertion position from token
        if ($token && str_starts_with($token, 'insert-')) {
            if ($token === 'insert-end') {
                // Append to end
                $count = ElementPage::where('page_id', $this->modelId)->count();
                $this->insertElementAt($count, $elementKey);
                return;
            }

            $index = (int)str_replace('insert-', '', $token);
            $this->insertElementAt($index, $elementKey);
        }
    }

    public function setViewMode(string $mode): void
    {
        $this->viewMode = $mode;
    }

    // Collection management methods
    public function syncCollections(Page $page): void
    {
        $collectionsWithPivot = [];
        
        foreach ($this->selectedCollectionIds as $index => $collectionId) {
            $collectionsWithPivot[$collectionId] = [
                'tenant_id' => auth()->user()->selected_tenant_id,
                'sort_order' => $index + 1,
            ];
        }
        
        $page->collections()->sync($collectionsWithPivot);
    }

    public function addCollection(int $collectionId): void
    {
        if (!in_array($collectionId, $this->selectedCollectionIds)) {
            $this->selectedCollectionIds[] = $collectionId;
        }
    }

    public function removeCollection(int $collectionId): void
    {
        $this->selectedCollectionIds = array_values(
            array_filter($this->selectedCollectionIds, fn($id) => $id !== $collectionId)
        );
    }

    public function reorderCollections(array $orderedIds): void
    {
        $this->selectedCollectionIds = $orderedIds;
    }
} ?>

<x-noerd::page :disableModal="$disableModal">
    <x-slot:header>
        <x-noerd::modal-title>{{ __('Page') }}</x-noerd::modal-title>
    </x-slot:header>

    <!-- View Mode Switch - Fixed Position -->
    <div class="ml-auto flex mb-6">
        <div class="flex space-x-1 bg-white p-1 rounded-lg w-fit shadow-xl border border-gray-200">
            <button
                wire:click="setViewMode('content')"
                class="px-4 py-2 rounded-md text-sm font-medium transition-colors {{ $viewMode === 'content' ? 'bg-gray-900 text-white shadow-sm' : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50' }}"
            >
                Content
            </button>
            <button
                wire:click="setViewMode('preview')"
                class="px-4 py-2 rounded-md text-sm font-medium transition-colors {{ $viewMode === 'preview' ? 'bg-gray-900 text-white shadow-sm' : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50' }}"
            >
                {{ __('Preview') }}
            </button>
            <div class="ml-auto mr-6 my-auto border-l border-gray-200 pl-4">
                <livewire:language-switcher/>
            </div>
        </div>
    </div>

    @include('noerd::components.detail.block', $pageLayout)

    <!-- Collections Section -->
    @if($this->page->id)
        <div class="mt-6 p-6 bg-white border border-gray-200 rounded-lg">
            <h3 class="text-lg font-medium text-gray-900 mb-4">{{ __('Linked Collections') }}</h3>
            
            <!-- Current Collections -->
            @if(count($this->pageCollections) > 0)
                <div class="space-y-2 mb-4">
                    @foreach($this->pageCollections as $collection)
                        <div class="flex items-center justify-between p-3 bg-gray-50 rounded-md">
                            <div class="flex-1">
                                <span class="font-medium">{{ $collection->name ?? $collection->collection_key }}</span>
                                <span class="text-sm text-gray-500 ml-2">({{ $collection->collection_key }})</span>
                            </div>
                            <x-noerd::buttons.delete 
                                wire:click="removeCollection({{ $collection->id }})"
                                wire:confirm="{{ __('Remove collection from page?') }}"
                                class="ml-2"
                            />
                        </div>
                    @endforeach
                </div>
            @else
                <p class="text-gray-500 text-sm mb-4">{{ __('No collections linked to this page') }}</p>
            @endif

            <!-- Add Collection -->
            <div class="flex gap-2">
                <select wire:model="selectedCollectionIds" multiple class="flex-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500">
                    @foreach($this->availableCollections as $collection)
                        <option value="{{ $collection->id }}">
                            {{ $collection->name ?? $collection->collection_key }} ({{ $collection->collection_key }})
                        </option>
                    @endforeach
                </select>
                <x-noerd::primary-button wire:click="store" class="shrink-0">
                    {{ __('Update Collections') }}
                </x-noerd::primary-button>
            </div>
        </div>
    @endif

    @if($this->page->id)
        <div x-data="{ viewMode: @entangle('viewMode').live }">
            <div x-show="viewMode === 'content'">
                <!-- Content View (Original Backend Editing) -->
                <button wire:click="openElements">
                    {{ __('Edit Page Elements') }}
                </button>

                <div x-sort="$wire.elementSort($item, $position)">
                    @foreach($this->page->elements as $loopIndex => $elementPage)
                        <div class="my-2">
                            <div x-data="{hover:false}" @mouseenter="hover=true" @mouseleave="hover=false"
                                 class="relative h-0.5 bg-transparent">
                                <button x-show="hover"
                                        class="absolute -top-3 left-0 right-0 mx-auto w-full max-w-sm flex items-center justify-center gap-2 text-white bg-blue-600/90 hover:bg-blue-700 rounded-full py-1 text-xs shadow"
                                        wire:click="$dispatch('noerdModal', {component: 'element-picker-modal', arguments: { token: 'insert-{{$loopIndex}}' }})">
                                    + {{ __('Add Element') }}
                                </button>
                            </div>
                        </div>

                        <div x-sort:item="{{$elementPage->id}}">
                            <livewire:element-page-component
                                wire:key="{{$elementPage->id . $lastChangeTime}}"
                                :modelId="$elementPage->id"
                            >
                            </livewire:element-page-component>
                        </div>
                    @endforeach

                    <div class="my-2">
                        <div x-data="{hover:false}" @mouseenter="hover=true" @mouseleave="hover=false"
                             class="relative h-0.5 bg-transparent">
                            <button x-show="hover"
                                    class="absolute -top-3 left-0 right-0 mx-auto w-full max-w-sm flex items-center justify-center gap-2 text-white bg-blue-600/90 hover:bg-blue-700 rounded-full py-1 text-xs shadow"
                                    wire:click="$dispatch('noerdModal', {component: 'element-picker-modal', arguments: { token: 'insert-end' }})">
                                + {{ __('Add Element') }}
                            </button>
                        </div>
                    </div>
                </div>

                <div class="mt-8 mb-8">
                    <x-noerd::title>{{__('Add Element')}}</x-noerd::title>
                    <div class="mt-4">
                        <x-noerd::primary-button
                            wire:click="$dispatch('noerdModal', {component: 'element-picker-modal', arguments: { token: 'insert-end' }})">
                            {{ __('Add Element') }}
                        </x-noerd::primary-button>
                    </div>
                </div>
            </div>
            <div x-show="viewMode === 'preview'">
                <!-- Preview View (Frontend Rendering) -->
                <div class="border border-gray-200 rounded-lg bg-white">
                    <div class="p-4 border-b border-gray-200 bg-gray-50">
                        <div class="flex items-center justify-between">
                            <div>
                                <h3 class="text-lg font-medium text-gray-900">{{ __('Frontend Preview') }}</h3>
                            </div>
                        </div>
                    </div>

                    <div class="p-6">
                        @if(count($this->livePreviewElements) > 0)
                            @foreach($this->livePreviewElements as $element)
                                @php
                                    $componentName = $this->componentMapping[$element['key']] ?? null;
                                    $componentExists = $componentName ? app(\Noerd\Website\Services\PageElementService::class)->elementDefinitionExists($componentName) : false;
                                @endphp

                                @if($componentExists)
                                    @livewire($componentName, ['data' => $element['data']], key('preview-element-' . $loop->index . '-' . $previewTick))
                                @else
                                    <!-- Fallback for missing or invalid element template -->
                                    <div
                                        class="p-4 border border-red-300 mb-4 sm:p-8 relative overflow-hidden rounded-lg bg-red-50 after:pointer-events-none after:absolute after:inset-0 after:rounded-lg after:inset-ring after:inset-ring-red-500/10">
                                        <div class="flex items-start justify-between gap-4">
                                            <div class="flex-1">
                                                <p class="text-sm font-semibold text-red-800">{{ __('Element component not found:') }} {{ $element['key'] ?? 'unknown' }}</p>
                                                <p class="text-xs text-red-700 mt-2">{{ __('Please create both the .yml and .blade.php files in the elements folder.') }}</p>
                                            </div>
                                            <div>
                                                <x-noerd::buttons.delete
                                                    wire:confirm="{{ __('Really delete element?') }}"
                                                    wire:click="deleteElement({{ (int) ($this->page->elements[$loop->index]->id ?? 0) }})"></x-noerd::buttons.delete>
                                            </div>
                                        </div>
                                        <details class="mt-2">
                                            <summary
                                                class="text-xs text-red-600 cursor-pointer">{{ __('Show data') }}</summary>
                                            <pre
                                                class="text-xs mt-2 text-red-700">{{ json_encode($element['data'] ?? [], JSON_PRETTY_PRINT) }}</pre>
                                        </details>
                                    </div>
                                @endif
                            @endforeach
                        @else
                            <div class="text-center py-8 text-gray-500">
                                <p>{{ __('No elements available') }}</p>
                                <p class="text-sm mt-1">{{ __('Switch to content mode to add elements') }}</p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    @endif

    <x-slot:footer>
        <x-noerd::delete-save-bar :showDelete="isset($page->id)"/>
    </x-slot:footer>

</x-noerd::page>
