<?php

use Illuminate\Support\Facades\Storage;
use Livewire\Attributes\Computed;
use Livewire\Attributes\On;
use Livewire\Attributes\Url;
use Livewire\Volt\Component;
use Livewire\WithFileUploads;
use Noerd\Cms\Helpers\CollectionHelper;
use Noerd\Cms\Helpers\FieldHelper;
use Noerd\Cms\Models\Collection;
use Noerd\Cms\Models\ElementPage;
use Noerd\Cms\Models\Language;
use Noerd\Cms\Models\Page;
use Noerd\Media\Models\Media;
use Noerd\Media\Services\MediaUploadService;
use Noerd\Noerd\Traits\Noerd;
use Noerd\Website\Services\PageElementService;

new class () extends Component {
    use Noerd;
    use WithFileUploads;

    public const COMPONENT = 'page-component';
    public const LIST_COMPONENT = 'pages-table';
    public const ID = 'pageId';
    #[Url(keep: false, except: '')]
    public $pageId = null;

    public array $model;
    public Page $page;
    public bool $slugAutoGenerated = false;
    public string $viewMode = 'content'; // 'content' or 'preview'
    public ?array $collectionLayout = null;
    public ?string $collectionKey = null;
    public array $images = [];

    public array $liveElementData = [];
    public int $previewTick = 0;

    #[Computed]
    public function hasPageFeatures(): bool
    {
        if (!$this->collectionKey || !$this->collectionLayout) {
            return true; // Regular pages always have page features
        }

        return $this->collectionLayout['hasPage'] ?? true;
    }

    #[Computed]
    public function elements()
    {
        return FieldHelper::getAllElements();
    }

    #[Computed]
    public function previewElements()
    {
        if (!$this->page->id) {
            return [];
        }

        $pageElementService = app(PageElementService::class);
        $selectedLanguage = session('selectedLanguage', 'de');

        return $pageElementService->processPageElements($this->page, $selectedLanguage);
    }


    #[Computed]
    public function livePreviewElements()
    {
        if (!$this->page->id) {
            return [];
        }

        try {
            // Get the base elements from database
            $pageElementService = app(PageElementService::class);
            $selectedLanguage = session('selectedLanguage', 'de');
            $elements = $pageElementService->processPageElements($this->page, $selectedLanguage);

            // Merge with live element data from form inputs
            foreach ($elements as $index => $element) {
                $elementPageId = $element['id'] ?? ($this->page->elements[$index]->id ?? null);
                if ($elementPageId && isset($this->liveElementData[$elementPageId])) {
                    // Ensure both are arrays before merging
                    $baseData = is_array($element['data'] ?? []) ? ($element['data'] ?? []) : [];
                    $liveData = is_array($this->liveElementData[$elementPageId]) ? $this->liveElementData[$elementPageId] : [];

                    // Process live data to ensure proper localization format
                    $processedLiveData = [];
                    foreach ($liveData as $key => $value) {
                        // If the value is already localized (array with language keys), keep it
                        if (is_array($value) && isset($value[$selectedLanguage])) {
                            $processedLiveData[$key] = $value[$selectedLanguage];
                        } elseif (is_array($value)) {
                            // If it's an array but not localized, try to get the first value or convert to string
                            $processedLiveData[$key] = is_string(reset($value)) ? reset($value) : json_encode($value);
                        } else {
                            // If it's already a string or simple value, use it directly
                            $processedLiveData[$key] = $value;
                        }
                    }

                    $elements[$index]['data'] = array_merge($baseData, $processedLiveData);
                }
            }

            return $elements;
        } catch (\Exception $e) {
            // Fallback to regular preview elements if something goes wrong
            \Log::error('Error in livePreviewElements: ' . $e->getMessage());
            return $this->previewElements;
        }
    }

    #[On('updateLiveElementData')]
    public function updateLiveElementData($elementPageId, $data): void
    {
        $this->liveElementData[$elementPageId] = $data;
        // Bump preview tick to force remount of preview child components only
        $this->previewTick++;
    }

    #[Computed]
    public function componentMapping()
    {
        $pageElementService = app(PageElementService::class);
        return $pageElementService->getComponentMapping();
    }

    /**
     * Returns available website layouts as key => label.
     */
    public function layoutOptions(): array
    {
        $layoutsDirectory = base_path('app-modules/website/resources/views/components/layouts');
        $options = [];

        if (is_dir($layoutsDirectory)) {
            foreach (glob($layoutsDirectory . '/*.blade.php') as $filePath) {
                $fileName = basename($filePath, '.blade.php');
                $options[$fileName] = $fileName;
            }
        }

        // Fallback to a sensible default if directory is empty
        if (empty($options)) {
            $options['weblayout'] = 'weblayout';
        }

        return $options;
    }

    public function mount(Page $model, ?string $collectionKey = null): void
    {
        if ($this->modelId) {
            $model = Page::find($this->modelId);
        }

        $this->page = $model;
        $this->collectionKey = $collectionKey;

        // Load collection layout if collectionKey is provided
        if ($this->collectionKey) {
            $this->collectionLayout = CollectionHelper::getCollectionFields($this->collectionKey);
        }

        $this->mountModalProcess(self::COMPONENT, $model);

        // Load data differently for collection pages vs regular pages
        if ($this->collectionKey && $model->data) {
            // For collection pages, load data from the JSON data field
            $this->model = is_array($model->data) ? $model->data : [];
        } else {
            // For regular pages, use the standard page fields
            $this->model = FieldHelper::parseComponentToData('page-component', $model->toArray());
        }

        // Ensure a layout is always preselected
        $availableLayouts = $this->layoutOptions();
        if (!isset($this->model['layout']) || empty($this->model['layout'])) {
            $this->model['layout'] = array_key_first($availableLayouts);
        }

        // Ensure sort field is available for collections
        if ($this->collectionKey) {
            $this->model['sort'] ??= $model->sort ?? 0;
        }

        // Fix slug field if it's malformed or shows [object Object]
        if (isset($this->model['slug'])) {
            // If slug is not an array or is malformed, reset it
            if (!is_array($this->model['slug']) || empty($this->model['slug'])) {
                $this->model['slug'] = ['de' => '', 'en' => ''];
            } else {
                // Ensure each language has a string value
                foreach (['de', 'en'] as $lang) {
                    if (!isset($this->model['slug'][$lang]) || !is_string($this->model['slug'][$lang])) {
                        $this->model['slug'][$lang] = '';
                    }
                }
            }
        } else {
            // Initialize empty slug array if not exists
            $this->model['slug'] = ['de' => '', 'en' => ''];
        }

        $this->lastChangeTime = time();


        // Initialize slugAutoGenerated flag
        // This is mainly used for preventing automatic updates of existing slugs
        // but we still allow generation for new languages
        $this->slugAutoGenerated = false;
    }

    public function getDefaultLanguageCode(): string
    {
        $defaultLanguage = Language::where('tenant_id', auth()->user()->selected_tenant_id)
            ->where('is_default', true)
            ->first();

        return $defaultLanguage ? $defaultLanguage->code : 'de';
    }

    public function generateSlug(string $name, ?string $languageCode = null): string
    {
        // Replace umlauts and special characters BEFORE lowercasing
        $slug = str_replace(['ä', 'ö', 'ü', 'ß', 'Ä', 'Ö', 'Ü'], ['ae', 'oe', 'ue', 'ss', 'ae', 'oe', 'ue'], $name);

        // Convert to lowercase
        $slug = mb_strtolower($slug);

        // Remove all non-alphanumeric characters and spaces, replace with hyphens
        $slug = preg_replace('/[^a-z0-9\s-]/', '', $slug);

        // Replace multiple spaces/hyphens with single hyphen
        $slug = preg_replace('/[\s-]+/', '-', $slug);

        // Trim hyphens from beginning and end
        $slug = mb_trim($slug, '-');

        // Add language prefix if not default language
        if ($languageCode && $languageCode !== $this->getDefaultLanguageCode()) {
            $slug = $languageCode . '/' . $slug;
        }

        // Ensure slug starts with forward slash
        return '/' . $slug;
    }

    public function updated($propertyName, $value): void
    {
        // Only handle name field updates
        if (!str_starts_with($propertyName, 'model.name.')) {
            return;
        }

        // Extract language from property name (e.g., 'model.name.de' -> 'de')
        $language = str_replace('model.name.', '', $propertyName);

        // Auto-generate slug if name has content and slug is empty for this language
        if (!empty($value)) {
            // Ensure slug array exists
            if (!isset($this->model['slug']) || !is_array($this->model['slug'])) {
                $this->model['slug'] = ['de' => '', 'en' => ''];
            }

            // Only generate slug if this specific language doesn't have a slug yet
            if (empty($this->model['slug'][$language] ?? '')) {
                $generatedSlug = $this->generateSlug($value, $language);
                $this->model['slug'][$language] = $generatedSlug;
            }
        }
    }

    public function store(): void
    {
        // Different validation for collection pages vs regular pages
        if ($this->collectionKey) {
            // For collection pages, validate collection-specific data
            $this->storeCollectionPage();
            return;
        }

        $this->validate([
            'model.name' => ['required', 'array', 'max:255'],
            'model.slug' => ['required', 'array'],
        ]);

        // Custom validation for slug format and uniqueness
        $validationErrors = [];
        if (isset($this->model['slug']) && is_array($this->model['slug'])) {
            foreach ($this->model['slug'] as $lang => $slug) {
                // Only validate slug if there's a corresponding name for this language
                if (!isset($this->model['name'][$lang]) || empty($this->model['name'][$lang])) {
                    continue;
                }

                if (empty($slug)) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} ist erforderlich.";
                    continue;
                }

                // Check if slug is string
                if (!is_string($slug)) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} muss ein Text sein.";
                    continue;
                }

                // Check if slug starts with forward slash
                if (!str_starts_with($slug, '/')) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} muss mit einem '/' beginnen.";
                    continue;
                }

                // Check slug format (only lowercase letters, numbers, hyphens, slashes, and forward slash at start)
                // Allow format: /slug or /lang/slug (where lang is 2-3 characters)
                if (!preg_match('/^\/([a-z]{2,3}\/)?[a-z0-9-]+$/', $slug)) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} darf nur Kleinbuchstaben, Zahlen, Bindestriche und optional einen Sprachprefix enthalten und muss mit '/' beginnen.";
                    continue;
                }

                // Check for duplicate slugs in database (excluding current record)
                $existingPage = \Noerd\Cms\Models\Page::where('tenant_id', auth()->user()->selected_tenant_id)
                    ->where('id', '!=', $this->modelId)
                    ->whereRaw("JSON_EXTRACT(slug, '$.{$lang}') = ?", [$slug])
                    ->first();

                if ($existingPage) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug '{$slug}' für Sprache {$lang} wird bereits verwendet.";
                }
            }
        }

        if (!empty($validationErrors)) {
            $this->addError('model.slug', reset($validationErrors));
            return;
        }

        $model = $this->model;
        $model['tenant_id'] = auth()->user()->selected_tenant_id;

        // Ensure layout is set before saving
        if (empty($model['layout'])) {
            $model['layout'] = array_key_first($this->layoutOptions());
        }

        // Clean up slug data before saving - remove empty values
        $cleanSlugData = [];
        if (isset($this->model['slug']) && is_array($this->model['slug'])) {
            foreach ($this->model['slug'] as $lang => $slug) {
                if (!empty($slug)) {
                    $cleanSlugData[$lang] = $slug;
                }
            }
        }

        // Laravel automatically casts these as JSON due to model casts
        $model['slug'] = $cleanSlugData;
        $model['name'] = $this->model['name'];


        $page = Page::updateOrCreate(
            ['id' => $this->modelId],
            $model,
        );

        $this->dispatch('storeElements');

        $this->showSuccessIndicator = true;

        if ($page->wasRecentlyCreated) {
            $this->modelId = $page['id'];
            $this->page = $page;
        }
    }

    public function updatedImages(): void
    {
        $mediaUploadService = app()->make(MediaUploadService::class);
        foreach ($this->images as $key => $image) {
            $media = $mediaUploadService->storeFromUploadedFile($image);
            $this->model[$key] = $this->urlWithoutDomain($media);
        }
    }

    public function deleteImage(string $fieldName): void
    {
        $this->model[$fieldName] = null;
    }

    public function openSelectMediaModal(string $fieldName): void
    {
        $token = uniqid('media_', true);
        $this->model['__mediaToken'] = $token;
        $this->dispatch(
            event: 'noerdModal',
            component: 'media-select-modal',
            arguments: ['context' => $fieldName, 'token' => $token],
        );
    }

    #[On('mediaSelected')]
    public function mediaSelected(int $mediaId, ?string $fieldName = 'image', ?string $token = null): void
    {
        if (($this->model['__mediaToken'] ?? null) !== $token) {
            return; // ignore events not intended for this instance
        }
        $media = Media::find($mediaId);
        if (!$media) {
            return;
        }
        $this->model[$fieldName ?? 'image'] = $this->urlWithoutDomain($media);
        unset($this->model['__mediaToken']);
    }

    public function delete(): void
    {
        $page = Page::find($this->modelId);
        $page->delete();
        $this->closeModalProcess(self::LIST_COMPONENT);
    }

    public function addElement($elementKey): void
    {
        $sortElement = ElementPage::where('page_id', $this->modelId)
            ->orderBy('sort', 'desc')
            ->first();

        ElementPage::create([
            'page_id' => $this->modelId,
            'element_key' => $elementKey,
            'sort' => ($sortElement?->sort ?? 0) + 1,
            'data' => '{}',
        ]);

        $this->lastChangeTime = time();
    }

    public function elementSort($elementId, $newPosition): void
    {
        $elements = ElementPage::where('page_id', $this->modelId)
            ->orderBy('sort')
            ->get();
        $loop = 0;
        foreach ($elements as $element) {
            if ($newPosition === $loop) {
                $loop++;
            }
            if ($element['id'] === $elementId) {
                $element->sort = $newPosition;
                $element->save();
            } else {
                $element->sort = $loop++;
                $element->save();
            }
        }
        $this->lastChangeTime = time();
    }

    public function deleteElement(int $elementPageId): void
    {
        $element = ElementPage::find($elementPageId);
        if ($element && (int) $element->page_id === (int) $this->modelId) {
            $element->delete();
            $this->lastChangeTime = time();
            $this->dispatch('reloadPageComponent');
        }
    }

    #[On('reloadPageComponent')]
    public function reloadPage(): void
    {
        $this->lastChangeTime = time();
    }

    #[On('languageChanged')]
    public function refresh(): void
    {
        $this->dispatch('$refresh');
    }

    public function openElements(): void
    {
        $this->dispatch(
            event: 'noerdModal',
            component: 'element-page-component',
            source: self::COMPONENT,
            arguments: ['modelId' => $this->pageId],
        );
    }

    public function setViewMode(string $mode): void
    {
        $this->viewMode = $mode;
    }

    private function storeCollectionPage(): void
    {
        // Find or create the parent Collection
        $parentCollection = Collection::firstOrCreate([
            'tenant_id' => auth()->user()->selected_tenant_id,
            'collection_key' => mb_strtoupper($this->collectionKey),
        ], [
            'name' => ucfirst($this->collectionKey), // Default name based on key
        ]);

        $hasPageFeatures = $this->collectionLayout['hasPage'] ?? true;

        $pageData = [
            'tenant_id' => auth()->user()->selected_tenant_id,
            'collection_id' => $parentCollection->id,
            'data' => $this->model,
            'sort' => (int) ($this->model['sort'] ?? 0),
        ];

        // Persist selected layout for collections as well
        $availableLayouts = $this->layoutOptions();
        $pageData['layout'] = $this->model['layout'] ?? array_key_first($availableLayouts);

        if ($hasPageFeatures) {
            // For collections with hasPage: true, store name and slug as JSON (translatable)
            $nameData = [];
            $slugData = [];

            if (isset($this->model['name']) && is_array($this->model['name'])) {
                foreach ($this->model['name'] as $lang => $nameValue) {
                    if (!empty($nameValue)) {
                        $nameData[$lang] = $nameValue;
                        $slugData[$lang] = $this->generateSlug($nameValue, $lang);
                    }
                }
            }

            // Fallback if no names provided
            if (empty($nameData)) {
                $nameData['de'] = 'Collection Page';
                $slugData['de'] = '/collection-page';
            }

            $pageData['name'] = $nameData;
            $pageData['slug'] = $slugData;
            $pageData['is_active'] = true;
        } else {
            // For collections with hasPage: false, use minimal page data
            $pageData['name'] = null;
            $pageData['slug'] = null;
            $pageData['is_active'] = false; // Use false instead of null for collections
        }

        $page = Page::updateOrCreate(['id' => $this->modelId], $pageData);

        $this->showSuccessIndicator = true;

        if ($page->wasRecentlyCreated) {
            $this->modelId = $page->id;
            $this->page = $page;
        }
    }

    private function urlWithoutDomain(Media $media): string
    {
        $url = Storage::disk($media->disk)->url($media->path);

        return mb_strstr($url, '/storage');
    }

} ?>

<x-noerd::page :disableModal="$disableModal">
    <x-slot:header>
        <x-noerd::modal-title>{{ __('Page') }}</x-noerd::modal-title>
    </x-slot:header>

    <!-- View Mode Switch - Fixed Position -->
    @if($this->hasPageFeatures)
        <div class="ml-auto flex mb-6">
            <div class="flex items-center space-x-4">
                <!-- Sort Field for Collections -->
                @if($collectionKey)
                    <div class="flex items-center space-x-2">
                        <label for="sort" class="text-sm text-gray-600 font-medium">Sort:</label>
                        <flux:input
                            wire:model="model.sort"
                            id="sort"
                            type="number"
                            class="w-16 text-sm"
                            min="0"
                            step="1"
                        />
                    </div>
                @endif

                <div class="flex space-x-1 bg-white p-1 rounded-lg w-fit shadow-xl border border-gray-200">
                    <button
                        wire:click="setViewMode('content')"
                        class="px-4 py-2 rounded-md text-sm font-medium transition-colors {{ $viewMode === 'content' ? 'bg-gray-900 text-white shadow-sm' : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50' }}"
                    >
                        Content
                    </button>
                    <button
                        wire:click="setViewMode('preview')"
                        class="px-4 py-2 rounded-md text-sm font-medium transition-colors {{ $viewMode === 'preview' ? 'bg-gray-900 text-white shadow-sm' : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50' }}"
                    >
                        {{ __('Preview') }}
                    </button>
                    <div class="ml-auto mr-6 my-auto border-l border-gray-200 pl-4">
                        <livewire:language-switcher/>
                    </div>
                </div>
            </div>
        </div>
    @else
        <!-- Language switcher and Sort field for collections without page features -->
        <div class="ml-auto flex mb-6">
            <div class="flex items-center space-x-4">
                <!-- Sort Field for Collections -->
                @if($collectionKey)
                    <div class="flex items-center space-x-2">
                        <label for="sort" class="text-sm text-gray-600 font-medium">Sort:</label>
                        <flux:input
                            wire:model="model.sort"
                            id="sort"
                            type="number"
                            class="w-16 text-sm"
                            min="0"
                            step="1"
                        />
                    </div>
                @endif

                <livewire:language-switcher/>
            </div>
        </div>
    @endif

    @if($this->hasPageFeatures)
        @include('noerd::components.detail.block', $pageLayout)
    @endif

    @if($collectionLayout)
        @include('noerd::components.detail.block', $collectionLayout)
    @endif


    @if($this->page->id && $this->hasPageFeatures)
        <div x-data="{ viewMode: @entangle('viewMode').live }">
            <div x-show="viewMode === 'content'">
                <!-- Content View (Original Backend Editing) -->
                <button wire:click="openElements">
                    {{ __('Edit Page Elements') }}
                </button>

                <div x-sort="$wire.elementSort($item, $position)">
                    @foreach($this->page->elements as $loopIndex => $elementPage)
                        <div x-sort:item="{{$elementPage->id}}" wire:key="sort-item-{{$elementPage->id}}">
                            <livewire:element-page-component
                                wire:key="element-page-{{$elementPage->id}}"
                                :modelId="$elementPage->id"
                            >
                            </livewire:element-page-component>
                        </div>
                    @endforeach

                    <div class="my-2">
                        <div x-data="{hover:false}" @mouseenter="hover=true" @mouseleave="hover=false"
                             class="relative h-0.5 bg-transparent">
                            <button x-show="hover"
                                    class="absolute -top-3 left-0 right-0 mx-auto w-full max-w-sm flex items-center justify-center gap-2 text-white bg-blue-600/90 hover:bg-blue-700 rounded-full py-1 text-xs shadow"
                                    wire:click="$dispatch('noerdModal', {component: 'element-picker-modal', arguments: { token: 'insert-end' }})">
                                + {{ __('Add Element') }}
                            </button>
                        </div>
                    </div>
                </div>

                <div class="mt-8 mb-8">
                    <x-noerd::title>{{__('Add Element')}}</x-noerd::title>
                    <div class="mt-4">
                        <x-noerd::primary-button
                            wire:click="$dispatch('noerdModal', {component: 'element-picker-modal', arguments: { token: 'insert-end' }})">
                            {{ __('Add Element') }}
                        </x-noerd::primary-button>
                    </div>
                </div>
            </div>
            <div x-show="viewMode === 'preview'">
                <!-- Preview View (Frontend Rendering) -->
                <div class="border border-gray-200 rounded-lg bg-white">
                    <div class="p-4 border-b border-gray-200 bg-gray-50">
                        <div class="flex items-center justify-between">
                            <div>
                                <h3 class="text-lg font-medium text-gray-900">{{ __('Frontend Preview') }}</h3>
                            </div>
                        </div>
                    </div>

                    <div class="p-6">
                        @if(count($this->livePreviewElements) > 0)
                            @foreach($this->livePreviewElements as $element)
                                @php
                                    $componentName = $this->componentMapping[$element['key']] ?? null;
                                    $componentExists = $componentName ? app(\Noerd\Website\Services\PageElementService::class)->elementDefinitionExists($componentName) : false;
                                @endphp

                                @if($componentExists)
                                    @livewire($componentName, ['data' => $element['data']], key('preview-element-' . $loop->index . '-' . $previewTick))
                                @else
                                    <!-- Fallback for missing or invalid element template -->
                                    <div
                                        class="p-4 border border-red-300 mb-4 sm:p-8 relative overflow-hidden rounded-lg bg-red-50 after:pointer-events-none after:absolute after:inset-0 after:rounded-lg after:inset-ring after:inset-ring-red-500/10">
                                        <div class="flex items-start justify-between gap-4">
                                            <div class="flex-1">
                                                <p class="text-sm font-semibold text-red-800">{{ __('Element component not found:') }} {{ $element['key'] ?? 'unknown' }}</p>
                                                <p class="text-xs text-red-700 mt-2">{{ __('Please create both the .yml and .blade.php files in the elements folder.') }}</p>
                                            </div>
                                            <div>
                                                <x-noerd::buttons.delete
                                                    wire:confirm="{{ __('Really delete element?') }}"
                                                    wire:click="deleteElement({{ (int) ($this->page->elements[$loop->index]->id ?? 0) }})"></x-noerd::buttons.delete>
                                            </div>
                                        </div>
                                        <details class="mt-2">
                                            <summary
                                                class="text-xs text-red-600 cursor-pointer">{{ __('Show data') }}</summary>
                                            <pre
                                                class="text-xs mt-2 text-red-700">{{ json_encode($element['data'] ?? [], JSON_PRETTY_PRINT) }}</pre>
                                        </details>
                                    </div>
                                @endif
                            @endforeach
                        @else
                            <div class="text-center py-8 text-gray-500">
                                <p>{{ __('No elements available') }}</p>
                                <p class="text-sm mt-1">{{ __('Switch to content mode to add elements') }}</p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    @endif

    <x-slot:footer>
        <x-noerd::delete-save-bar :showDelete="isset($page->id)"/>
    </x-slot:footer>

</x-noerd::page>
