<?php

use Livewire\Attributes\Computed;
use Livewire\Attributes\On;
use Livewire\Attributes\Url;
use Livewire\Volt\Component;
use Noerd\Cms\Helpers\FieldHelper;
use Noerd\Cms\Models\ElementPage;
use Noerd\Cms\Models\Language;
use Noerd\Cms\Models\Page;
use Noerd\Website\Services\PageElementService;
use Noerd\Noerd\Traits\Noerd;

new class extends Component {

    use Noerd;

    public const COMPONENT = 'page-component';
    public const LIST_COMPONENT = 'pages-table';
    public const ID = 'pageId';
    #[Url(keep: false, except: '')]
    public $pageId = null;

    public array $model;
    public Page $page;
    public bool $slugAutoGenerated = false;
    public string $viewMode = 'content'; // 'content' or 'preview'

    #[Computed]
    public function elements()
    {
        return FieldHelper::getAllElements();
    }

    #[Computed]
    public function previewElements()
    {
        if (!$this->page->id) {
            return [];
        }

        $pageElementService = app(PageElementService::class);
        $selectedLanguage = session('selectedLanguage', 'de');

        return $pageElementService->processPageElements($this->page, $selectedLanguage);
    }

    public array $liveElementData = [];
    public int $previewTick = 0;

    #[Computed]
    public function livePreviewElements()
    {
        if (!$this->page->id) {
            return [];
        }

        try {
            // Get the base elements from database
            $pageElementService = app(PageElementService::class);
            $selectedLanguage = session('selectedLanguage', 'de');
            $elements = $pageElementService->processPageElements($this->page, $selectedLanguage);

            // Merge with live element data from form inputs
            foreach ($elements as $index => $element) {
                $elementPageId = $element['id'] ?? ($this->page->elements[$index]->id ?? null);
                if ($elementPageId && isset($this->liveElementData[$elementPageId])) {
                    // Ensure both are arrays before merging
                    $baseData = is_array($element['data'] ?? []) ? ($element['data'] ?? []) : [];
                    $liveData = is_array($this->liveElementData[$elementPageId]) ? $this->liveElementData[$elementPageId] : [];

                    // Process live data to ensure proper localization format
                    $processedLiveData = [];
                    foreach ($liveData as $key => $value) {
                        // If the value is already localized (array with language keys), keep it
                        if (is_array($value) && isset($value[$selectedLanguage])) {
                            $processedLiveData[$key] = $value[$selectedLanguage];
                        } elseif (is_array($value)) {
                            // If it's an array but not localized, try to get the first value or convert to string
                            $processedLiveData[$key] = is_string(reset($value)) ? reset($value) : json_encode($value);
                        } else {
                            // If it's already a string or simple value, use it directly
                            $processedLiveData[$key] = $value;
                        }
                    }

                    $elements[$index]['data'] = array_merge($baseData, $processedLiveData);
                }
            }

            return $elements;
        } catch (\Exception $e) {
            // Fallback to regular preview elements if something goes wrong
            \Log::error('Error in livePreviewElements: ' . $e->getMessage());
            return $this->previewElements;
        }
    }

    #[On('updateLiveElementData')]
    public function updateLiveElementData($elementPageId, $data)
    {
        $this->liveElementData[$elementPageId] = $data;
        // Bump preview tick to force remount of preview child components only
        $this->previewTick++;
    }

    #[Computed]
    public function componentMapping()
    {
        $pageElementService = app(PageElementService::class);
        return $pageElementService->getComponentMapping();
    }

    public function mount(Page $model): void
    {
        if ($this->modelId) {
            $model = Page::find($this->modelId);
        }

        $this->page = $model;
        $this->mountModalProcess(self::COMPONENT, $model);

        // Special case for Page/Element fields
        $this->model = FieldHelper::parseComponentToData('page-component', $model->toArray());

        // Fix slug field if it's malformed or shows [object Object]
        if (isset($this->model['slug'])) {
            // If slug is not an array or is malformed, reset it
            if (!is_array($this->model['slug']) || empty($this->model['slug'])) {
                $this->model['slug'] = ['de' => '', 'en' => ''];
            } else {
                // Ensure each language has a string value
                foreach (['de', 'en'] as $lang) {
                    if (!isset($this->model['slug'][$lang]) || !is_string($this->model['slug'][$lang])) {
                        $this->model['slug'][$lang] = '';
                    }
                }
            }
        } else {
            // Initialize empty slug array if not exists
            $this->model['slug'] = ['de' => '', 'en' => ''];
        }

        $this->lastChangeTime = time();

        // Initialize slugAutoGenerated flag
        // This is mainly used for preventing automatic updates of existing slugs
        // but we still allow generation for new languages
        $this->slugAutoGenerated = false;
    }

    public function getDefaultLanguageCode(): string
    {
        $defaultLanguage = Language::where('tenant_id', auth()->user()->selected_tenant_id)
            ->where('is_default', true)
            ->first();

        return $defaultLanguage ? $defaultLanguage->code : 'de';
    }

    public function generateSlug(string $name, string $languageCode = null): string
    {
        // Replace umlauts and special characters BEFORE lowercasing
        $slug = str_replace(['ä', 'ö', 'ü', 'ß', 'Ä', 'Ö', 'Ü'], ['ae', 'oe', 'ue', 'ss', 'ae', 'oe', 'ue'], $name);

        // Convert to lowercase
        $slug = strtolower($slug);

        // Remove all non-alphanumeric characters and spaces, replace with hyphens
        $slug = preg_replace('/[^a-z0-9\s-]/', '', $slug);

        // Replace multiple spaces/hyphens with single hyphen
        $slug = preg_replace('/[\s-]+/', '-', $slug);

        // Trim hyphens from beginning and end
        $slug = trim($slug, '-');

        // Add language prefix if not default language
        if ($languageCode && $languageCode !== $this->getDefaultLanguageCode()) {
            $slug = $languageCode . '/' . $slug;
        }

        // Ensure slug starts with forward slash
        return '/' . $slug;
    }

    public function updated($propertyName, $value): void
    {
        // Only handle name field updates
        if (!str_starts_with($propertyName, 'model.name.')) {
            return;
        }

        // Extract language from property name (e.g., 'model.name.de' -> 'de')
        $language = str_replace('model.name.', '', $propertyName);

        // Auto-generate slug if name has content and slug is empty for this language
        if (!empty($value)) {
            // Ensure slug array exists
            if (!isset($this->model['slug']) || !is_array($this->model['slug'])) {
                $this->model['slug'] = ['de' => '', 'en' => ''];
            }

            // Only generate slug if this specific language doesn't have a slug yet
            if (empty($this->model['slug'][$language] ?? '')) {
                $generatedSlug = $this->generateSlug($value, $language);
                $this->model['slug'][$language] = $generatedSlug;
            }
        }
    }

    public function store(): void
    {
        $this->validate([
            'model.name' => ['required', 'array', 'max:255'],
            'model.slug' => ['required', 'array'],
        ]);

        // Custom validation for slug format and uniqueness
        $validationErrors = [];
        if (isset($this->model['slug']) && is_array($this->model['slug'])) {
            foreach ($this->model['slug'] as $lang => $slug) {
                // Only validate slug if there's a corresponding name for this language
                if (!isset($this->model['name'][$lang]) || empty($this->model['name'][$lang])) {
                    continue;
                }

                if (empty($slug)) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} ist erforderlich.";
                    continue;
                }

                // Check if slug is string
                if (!is_string($slug)) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} muss ein Text sein.";
                    continue;
                }

                // Check if slug starts with forward slash
                if (!str_starts_with($slug, '/')) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} muss mit einem '/' beginnen.";
                    continue;
                }

                // Check slug format (only lowercase letters, numbers, hyphens, slashes, and forward slash at start)
                // Allow format: /slug or /lang/slug (where lang is 2-3 characters)
                if (!preg_match('/^\/([a-z]{2,3}\/)?[a-z0-9-]+$/', $slug)) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug für Sprache {$lang} darf nur Kleinbuchstaben, Zahlen, Bindestriche und optional einen Sprachprefix enthalten und muss mit '/' beginnen.";
                    continue;
                }

                // Check for duplicate slugs in database (excluding current record)
                $existingPage = \Noerd\Cms\Models\Page::where('tenant_id', auth()->user()->selected_tenant_id)
                    ->where('id', '!=', $this->modelId)
                    ->whereRaw("JSON_EXTRACT(slug, '$.{$lang}') = ?", [$slug])
                    ->first();

                if ($existingPage) {
                    $validationErrors["model.slug.{$lang}"] = "Der Slug '{$slug}' für Sprache {$lang} wird bereits verwendet.";
                }
            }
        }

        if (!empty($validationErrors)) {
            $this->addError('model.slug', reset($validationErrors));
            return;
        }

        $model = $this->model;
        $model['tenant_id'] = auth()->user()->selected_tenant_id;

        // Clean up slug data before saving - remove empty values
        $cleanSlugData = [];
        if (isset($this->model['slug']) && is_array($this->model['slug'])) {
            foreach ($this->model['slug'] as $lang => $slug) {
                if (!empty($slug)) {
                    $cleanSlugData[$lang] = $slug;
                }
            }
        }

        // TODO auto detect if value is an array and convert it to JSON
        $model['slug'] = json_encode($cleanSlugData);
        $model['name'] = json_encode($this->model['name']);


        $page = Page::updateOrCreate(['id' => $this->modelId],
            $model);

        $this->dispatch('storeElements');
        $this->showSuccessIndicator = true;

        if ($page->wasRecentlyCreated) {
            $this->modelId = $page['id'];
            $this->page = $page;
        }
    }

    public function delete(): void
    {
        $page = Page::find($this->modelId);
        $page->delete();
        $this->closeModalProcess(self::LIST_COMPONENT);
    }

    public function addElement($elementKey)
    {
        $sortElement = ElementPage::where('page_id', $this->modelId)
            ->orderBy('sort', 'desc')
            ->first();

        ElementPage::create([
            'page_id' => $this->modelId,
            'element_key' => $elementKey,
            'sort' => ($sortElement?->sort ?? 0) + 1,
            'data' => '{}',
        ]);

        $this->lastChangeTime = time();
    }

    public function elementSort($elementId, $newPosition): void
    {
        $elements = ElementPage::where('page_id', $this->modelId)
            ->orderBy('sort')
            ->get();
        $loop = 0;
        foreach ($elements as $element) {
            if ($newPosition === $loop) {
                $loop++;
            }
            if ($element['id'] === $elementId) {
                $element->sort = $newPosition;
                $element->save();
            } else {
                $element->sort = $loop++;
                $element->save();
            }
        }
        $this->lastChangeTime = time();
    }

    #[On('reloadPageComponent')]
    public function reloadPage()
    {
        $this->lastChangeTime = time();
    }

    #[On('languageChanged')]
    public function refresh()
    {
        $this->dispatch('$refresh');
    }

    public function openElements()
    {
        $this->dispatch(
            event: 'noerdModal',
            component: 'element-page-component',
            source: self::COMPONENT,
            arguments: ['modelId' => $this->pageId],
        );
    }

    public function setViewMode(string $mode): void
    {
        $this->viewMode = $mode;
    }
} ?>

<x-noerd::page :disableModal="$disableModal">
    <x-slot:header>
        <x-noerd::modal-title>Seite</x-noerd::modal-title>
    </x-slot:header>

    <!-- View Mode Switch - Fixed Position -->
    <div class="sticky top-20 right-6 z-50 mb-6">
        <div class="flex space-x-1 bg-white p-1 rounded-lg w-fit shadow-xl border border-gray-200">
            <button
                wire:click="setViewMode('content')"
                class="px-4 py-2 rounded-md text-sm font-medium transition-colors {{ $viewMode === 'content' ? 'bg-gray-900 text-white shadow-sm' : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50' }}"
            >
                Content
            </button>
            <button
                wire:click="setViewMode('preview')"
                class="px-4 py-2 rounded-md text-sm font-medium transition-colors {{ $viewMode === 'preview' ? 'bg-gray-900 text-white shadow-sm' : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50' }}"
            >
                Vorschau
            </button>
            <div class="ml-auto mr-6 my-auto border-l border-gray-200 pl-4">
                <livewire:language-switcher/>
            </div>
        </div>
    </div>

    @include('noerd::components.detail.block', $pageLayout)

    @if($this->page->id)
        <div x-data="{ viewMode: @entangle('viewMode').live }">
            <div x-show="viewMode === 'content'">
            <!-- Content View (Original Backend Editing) -->
            <button wire:click="openElements">
                Seitenelemente bearbeiten
            </button>

            <div x-sort="$wire.elementSort($item, $position)">
                @foreach($this->page->elements as $elementPage)
                    <div x-sort:item="{{$elementPage->id}}">
                        <livewire:element-page-component
                            wire:key="{{$elementPage->id . $lastChangeTime}}"
                            :modelId="$elementPage->id"
                        >
                        </livewire:element-page-component>
                    </div>
                @endforeach
            </div>

            <div class="mt-4">
                <x-noerd::title>Element hinzufügen</x-noerd::title>
                <div class="mt-4">
                    <div class="grid grid-cols-3 gap-8">
                        @foreach($this->elements() as $element)
                            <div wire:click="addElement('{{$element->element_key}}')"
                                 class="text-sm hover:bg-gray-200 bg-gray-100 cursor-pointer border-dotted border p-4 text-center">
                                <div class="font-bold"> {{$element->name}} </div>
                                {{$element->description}}
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
            </div>
            <div x-show="viewMode === 'preview'">
            <!-- Preview View (Frontend Rendering) -->
            <div class="border border-gray-200 rounded-lg bg-white">
                <div class="p-4 border-b border-gray-200 bg-gray-50">
                    <div class="flex items-center justify-between">
                        <div>
                            <h3 class="text-lg font-medium text-gray-900">Frontend Vorschau</h3>
                        </div>
                    </div>
                </div>

                <div class="p-6">
                    @if(count($this->livePreviewElements) > 0)
                        @foreach($this->livePreviewElements as $element)
                            @php
                                $componentName = $this->componentMapping[$element['key']] ?? null;
                            @endphp

                            @if($componentName)
                                @livewire($componentName, ['data' => $element['data']], key('preview-element-' . $loop->index . '-' . $previewTick))
                            @else
                                <!-- Fallback for missing or invalid element template -->
                                <div class="p-4 bg-yellow-50 border border-yellow-200 rounded mb-4">
                                    <p class="text-sm text-yellow-800 font-medium">Element-Komponente nicht
                                        gefunden: {{ $element['key'] ?? 'unknown' }}</p>
                                    <details class="mt-2">
                                        <summary class="text-xs text-yellow-600 cursor-pointer">Daten anzeigen</summary>
                                        <pre
                                            class="text-xs mt-2 text-yellow-700">{{ json_encode($element['data'] ?? [], JSON_PRETTY_PRINT) }}</pre>
                                    </details>
                                </div>
                            @endif
                        @endforeach
                    @else
                        <div class="text-center py-8 text-gray-500">
                            <p>Keine Elemente vorhanden</p>
                            <p class="text-sm mt-1">Wechseln Sie zum Content-Modus, um Elemente hinzuzufügen</p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    @endif

    <x-slot:footer>
        <x-noerd::delete-save-bar :showDelete="isset($page->id)"/>
    </x-slot:footer>
</x-noerd::page>
