<?php

use Illuminate\Support\Facades\Storage;
use Livewire\Attributes\Computed;
use Livewire\Attributes\On;
use Livewire\Attributes\Url;
use Livewire\Volt\Component;
use Livewire\WithFileUploads;
use Noerd\Cms\Helpers\CollectionHelper;
use Noerd\Cms\Helpers\FieldHelper;
use Noerd\Cms\Models\Collection;
use Noerd\Cms\Models\ElementPage;
use Noerd\Cms\Models\Page;
use Noerd\Cms\Services\FieldTypeConverter;
use Noerd\Media\Models\Media;
use Noerd\Media\Services\MediaUploadService;
use Noerd\Cms\Models\CmsLanguage;
use Noerd\Noerd\Traits\Noerd;

new class () extends Component {
    use Noerd;
    use WithFileUploads;

    public const COMPONENT = 'page-detail';
    public const LIST_COMPONENT = 'pages-list';
    public const ID = 'pageId';
    #[Url(keep: false, except: '')]
    public $pageId = null;

    public array $pageData = [];
    public bool $slugAutoGenerated = false;

    #[Computed]
    public function pageModel(): ?Page
    {
        if (!$this->pageId) {
            return null;
        }

        return Page::with('elements')->find($this->pageId);
    }

    public ?array $collectionLayout = null;
    public ?string $collectionKey = null;
    public array $images = [];

    public string $hrefPage = '';

    #[Computed]
    public function hasPageFeatures(): bool
    {
        if (!$this->collectionKey || !$this->collectionLayout) {
            return true; // Regular pages always have page features
        }

        return $this->collectionLayout['hasPage'] ?? true;
    }

    #[Computed]
    public function elements()
    {
        return FieldHelper::getAllElements();
    }

    public function layoutOptions(): array
    {
        $layoutsDirectory = base_path('app-modules/website/resources/views/components/layouts');
        $options = [];

        if (is_dir($layoutsDirectory)) {
            foreach (glob($layoutsDirectory . '/*.blade.php') as $filePath) {
                $fileName = basename($filePath, '.blade.php');

                // Skip include files that start with underscore
                if (str_starts_with($fileName, '_')) {
                    continue;
                }

                $options[$fileName] = $fileName;
            }
        }

        // Fallback to a sensible default if directory is empty
        if (empty($options)) {
            $options['weblayout'] = 'weblayout';
        }

        return $options;
    }

    public function mount(Page $page, ?string $collectionKey = null): void
    {
        if ($this->pageId) {
            $page = Page::find($this->pageId);
        }

        $this->pageId = $page->id;
        $this->collectionKey = $collectionKey;

        // Load collection layout if collectionKey is provided
        if ($this->collectionKey) {
            $this->collectionLayout = CollectionHelper::getCollectionFields($this->collectionKey);
        }

        $this->mountModalProcess(self::COMPONENT, $page);

        // Load data differently for collection pages vs regular pages
        //   if ($this->collectionKey && $page->data) {
        //       // For collection pages, load data from the JSON data field
        //        $rawData = is_array($page->data) ? $page->data : [];
        //        // Apply field type conversion when loading existing entries
        //        // This ensures users see the correct field structure immediately
        // $this->pageData = FieldTypeConverter::convertCollectionData($rawData, $this->collectionKey);
        //    } else {
        //       // For regular pages, use the standard page fields
        //        $this->pageData = FieldHelper::parseComponentToData('page-detail', $page->toArray());
        //    }

        $this->pageData = $page->toArray();

        // For collection entries: Merge data from the data column into pageData for proper wire:model binding
        if ($this->collectionKey && isset($this->pageData['data']) && is_array($this->pageData['data'])) {
            foreach ($this->pageData['data'] as $key => $value) {
                // Only merge collection fields, skip internal keys
                if (!str_starts_with($key, 'pageData.')) {
                    $this->pageData[$key] = $value;
                }
            }
        }

        // Ensure a layout is always preselected
        $availableLayouts = $this->layoutOptions();
        if (!isset($this->pageData['layout']) || empty($this->pageData['layout'])) {
            $this->pageData['layout'] = array_key_first($availableLayouts);
        }

        // Ensure sort field is available for collections
        if ($this->collectionKey) {
            $this->pageData['sort'] ??= $page->sort ?? 0;
        }

        // Fix slug field if it's malformed or shows [object Object]
        $activeLangCodes = $this->getActiveTenantLanguageCodes();
        if (empty($activeLangCodes)) {
            $activeLangCodes = [$this->getDefaultLanguageCode()];
        }

        if (isset($this->pageData['slug'])) {
            // If slug is not an array or is malformed, reset it
            if (!is_array($this->pageData['slug']) || empty($this->pageData['slug'])) {
                $this->pageData['slug'] = $this->initializeEmptySlugArray();
            } else {
                // Ensure each active language has a string value
                foreach ($activeLangCodes as $lang) {
                    if (!isset($this->pageData['slug'][$lang]) || !is_string($this->pageData['slug'][$lang])) {
                        $this->pageData['slug'][$lang] = '';
                    }
                }
            }
        } else {
            // Initialize empty slug array if not exists
            $this->pageData['slug'] = $this->initializeEmptySlugArray();
        }

        $this->lastChangeTime = time();

        $this->slugAutoGenerated = false;
    }

    public function getDefaultLanguageCode(): string
    {
        $defaultLanguage = CmsLanguage::where('tenant_id', auth()->user()->selected_tenant_id)
            ->where('is_default', true)
            ->first();

        return $defaultLanguage?->code ?? 'en';
    }

    public function getActiveTenantLanguageCodes(): array
    {
        return CmsLanguage::where('tenant_id', auth()->user()->selected_tenant_id)
            ->where('is_active', true)
            ->orderBy('is_default', 'desc')
            ->pluck('code')
            ->toArray();
    }

    private function initializeEmptySlugArray(): array
    {
        $languages = $this->getActiveTenantLanguageCodes();
        if (empty($languages)) {
            $languages = [$this->getDefaultLanguageCode()];
        }
        return array_fill_keys($languages, '');
    }

    public function generateSlug(string $name, ?string $languageCode = null): string
    {
        // Replace umlauts and special characters BEFORE lowercasing
        $slug = str_replace(['ä', 'ö', 'ü', 'ß', 'Ä', 'Ö', 'Ü'], ['ae', 'oe', 'ue', 'ss', 'ae', 'oe', 'ue'], $name);

        // Convert to lowercase
        $slug = mb_strtolower($slug);

        // Remove all non-alphanumeric characters and spaces, replace with hyphens
        $slug = preg_replace('/[^a-z0-9\s-]/', '', $slug);

        // Replace multiple spaces/hyphens with single hyphen
        $slug = preg_replace('/[\s-]+/', '-', $slug);

        // Trim hyphens from beginning and end
        $slug = mb_trim($slug, '-');

        // Add language prefix if not default language
        if ($languageCode && $languageCode !== $this->getDefaultLanguageCode()) {
            $slug = $languageCode . '/' . $slug;
        }

        // Ensure slug starts with forward slash
        return '/' . $slug;
    }

    public function updated($propertyName, $value): void
    {
        // Only handle name field updates
        if (!str_starts_with($propertyName, 'pageData.name.')) {
            return;
        }

        // Extract language from property name (e.g., 'pageData.name.de' -> 'de')
        $language = str_replace('pageData.name.', '', $propertyName);

        // Auto-generate slug if name has content and slug is empty for this language
        if (!empty($value)) {
            // Ensure slug array exists
            if (!isset($this->pageData['slug']) || !is_array($this->pageData['slug'])) {
                $this->pageData['slug'] = $this->initializeEmptySlugArray();
            }

            // Only generate slug if this specific language doesn't have a slug yet
            if (empty($this->pageData['slug'][$language] ?? '')) {
                $generatedSlug = $this->generateSlug($value, $language);
                $this->pageData['slug'][$language] = $generatedSlug;
            }
        }
    }

    public function store(): void
    {
        // Different validation for collection pages vs regular pages
        if ($this->collectionKey) {
            // For collection pages, validate collection-specific data
            $this->storeCollectionPage();
            return;
        }

        $this->validate([
            'pageData.name' => ['required', 'array', 'max:255'],
            'pageData.slug' => ['required', 'array'],
        ]);

        if (!empty($validationErrors)) {
            $this->addError('pageData.slug', reset($validationErrors));
            return;
        }

        $data = $this->pageData;
        $data['tenant_id'] = auth()->user()->selected_tenant_id;

        // Ensure layout is set before saving
        if (empty($data['layout'])) {
            $data['layout'] = array_key_first($this->layoutOptions());
        }

        // Clean up slug data before saving - remove empty values
        $cleanSlugData = [];
        if (isset($this->pageData['slug']) && is_array($this->pageData['slug'])) {
            foreach ($this->pageData['slug'] as $lang => $slug) {
                if (!empty($slug)) {
                    $cleanSlugData[$lang] = $slug;
                }
            }
        }

        $data['slug'] = $cleanSlugData;
        $data['name'] = $this->pageData['name'];

        $page = Page::updateOrCreate(
            ['id' => $this->pageId],
            $data,
        );

        $this->dispatch('storeElements');

        $this->showSuccessIndicator = true;

        if ($page->wasRecentlyCreated) {
            $this->pageId = $page->id;
        }
    }

    public function updatedImages(): void
    {
        $mediaUploadService = app()->make(MediaUploadService::class);
        foreach ($this->images as $key => $image) {
            $media = $mediaUploadService->storeFromUploadedFile($image);
            $this->pageData[$key] = $this->urlWithoutDomain($media);
        }
    }

    public function deleteImage(string $fieldName): void
    {
        $this->pageData[$fieldName] = null;
    }

    public function openSelectMediaModal(string $fieldName): void
    {
        $token = uniqid('media_', true);
        $this->pageData['__mediaToken'] = $token;
        $this->dispatch(
            event: 'noerdModal',
            component: 'media-list',
            arguments: ['selectMode' => true, 'selectContext' => $fieldName, 'selectToken' => $token],
        );
    }

    #[On('mediaSelected')]
    public function mediaSelected(int $mediaId, ?string $fieldName = 'image', ?string $token = null): void
    {
        if (($this->pageData['__mediaToken'] ?? null) !== $token) {
            return; // ignore events not intended for this instance
        }
        $media = Media::find($mediaId);
        if (!$media) {
            return;
        }
        $this->pageData[$fieldName ?? 'image'] = $this->urlWithoutDomain($media);
        unset($this->pageData['__mediaToken']);
    }

    public function delete(): void
    {
        $page = Page::find($this->pageId);
        $page->delete();
        $this->closeModalProcess(self::LIST_COMPONENT);
    }

    #[On('elementPicked')]
    public function addElement($elementKey): void
    {
        $sortElement = ElementPage::where('page_id', $this->pageId)
            ->orderBy('sort', 'desc')
            ->first();

        ElementPage::create([
            'page_id' => $this->pageId,
            'element_key' => $elementKey,
            'sort' => ($sortElement?->sort ?? 0) + 1,
            'data' => '{}',
        ]);

        $this->lastChangeTime = time();
    }

    #[On('pageSelected')]
    public function pageSelected($value, $context): void
    {
        $page = Page::find($value);
        $this->hrefPage = $page['name'][session('selectedLanguage')];
        $this->relationTitles[$value] = $page['name'][session('selectedLanguage')];
        $this->pageData[str_replace('pageData.', '', $context)] = $page->id;
    }

    public function elementSort($elementId, $newPosition): void
    {
        $elements = ElementPage::where('page_id', $this->pageId)
            ->orderBy('sort')
            ->get();
        $loop = 0;
        foreach ($elements as $element) {
            if ($newPosition === $loop) {
                $loop++;
            }
            if ($element['id'] === $elementId) {
                $element->sort = $newPosition;
                $element->save();
            } else {
                $element->sort = $loop++;
                $element->save();
            }
        }
        $this->lastChangeTime = time();
    }

    public function deleteElement(int $elementPageId): void
    {
        $element = ElementPage::find($elementPageId);
        if ($element && (int)$element->page_id === (int)$this->pageId) {
            $element->delete();
            $this->lastChangeTime = time();
            $this->dispatch('reloadPageComponent');
        }
    }

    #[On('reloadPageComponent')]
    public function reloadPage(): void
    {
        $this->lastChangeTime = time();
    }

    #[On('languageChanged')]
    public function refresh(): void
    {
        $this->dispatch('$refresh');
    }

    public function openElements(): void
    {
        $this->dispatch(
            event: 'noerdModal',
            component: 'element-page-detail',
            source: self::COMPONENT,
            arguments: ['elementPageId' => $this->pageId],
        );
    }

    public function getPageUrl(): ?string
    {
        $selectedLanguage = session('selectedLanguage') ?? $this->getDefaultLanguageCode();
        $slug = $this->pageData['slug'][$selectedLanguage] ?? null;

        if (!$slug) {
            return null;
        }

        return url($slug);
    }

    private function storeCollectionPage(): void
    {
        // Find or create the parent Collection
        $parentCollection = Collection::firstOrCreate([
            'tenant_id' => auth()->user()->selected_tenant_id,
            'collection_key' => mb_strtoupper($this->collectionKey),
        ], [
            'name' => ucfirst($this->collectionKey), // Default name based on key
        ]);

        $hasPageFeatures = $this->collectionLayout['hasPage'] ?? true;

        // Apply field type conversion before saving
        $convertedData = FieldTypeConverter::convertCollectionData($this->pageData, $this->collectionKey);

        $data = [
            'tenant_id' => auth()->user()->selected_tenant_id,
            'collection_id' => $parentCollection->id,
            'data' => $convertedData,
            'sort' => (int)($this->pageData['sort'] ?? 0),
        ];

        // Persist selected layout for collections as well
        $availableLayouts = $this->layoutOptions();
        $data['layout'] = $this->pageData['layout'] ?? array_key_first($availableLayouts);

        if ($hasPageFeatures) {
            // For collections with hasPage: true, store name and slug as JSON (translatable)
            $nameData = [];
            $slugData = [];

            if (isset($convertedData['name']) && is_array($convertedData['name'])) {
                foreach ($convertedData['name'] as $lang => $nameValue) {
                    if (!empty($nameValue)) {
                        $nameData[$lang] = $nameValue;
                        $slugData[$lang] = $this->generateSlug($nameValue, $lang);
                    }
                }
            }

            // Fallback if no names provided - use tenant's default language
            if (empty($nameData)) {
                $defaultLang = $this->getDefaultLanguageCode();
                $nameData[$defaultLang] = 'Collection Page';
                $slugData[$defaultLang] = '/collection-page';
            }

            $data['name'] = $nameData;
            $data['slug'] = $slugData;
            $data['is_active'] = true;
        } else {
            // For collections with hasPage: false, use minimal page data
            $data['name'] = null;
            $data['slug'] = null;
            $data['is_active'] = true; // Collection pages without page features are always active
        }

        $page = Page::updateOrCreate(['id' => $this->pageId], $data);

        $this->showSuccessIndicator = true;

        if ($page->wasRecentlyCreated) {
            $this->pageId = $page->id;
        }
    }

    private function urlWithoutDomain(Media $media): string
    {
        $url = Storage::disk($media->disk)->url($media->path);

        return mb_strstr($url, '/storage');
    }

} ?>

<x-noerd::page :disableModal="$disableModal">

    <x-slot:header>
        <x-noerd::modal-title class="flex items-center">
            {{ __('Page') }}

            <div class="ml-auto" :class="isModal ? 'mr-22' : ''">
                <div class="flex items-center gap-4">
                    <livewire:language-switcher/>

                    @if($this->pageModel?->id && $this->hasPageFeatures)
                        @php $pageUrl = $this->getPageUrl(); @endphp
                        @if($pageUrl)
                            <a href="{{ $pageUrl }}" target="_blank"
                               class="px-4 py-2 rounded-md text-sm font-medium bg-gray-900 text-white hover:bg-gray-800 transition-colors">
                                {{ __('Zur Seite') }}
                            </a>
                        @endif
                    @endif
                </div>
            </div>

        </x-noerd::modal-title>
    </x-slot:header>
    <div>
        <!-- Sort Field for Collections -->
        @if($collectionKey)
            <div class="flex">
                <div class="flex ml-auto items-center my-6 space-x-4">
                    <div class="flex ml-auto items-center space-x-2">
                        <label for="sort" class="text-sm text-gray-600 font-medium">Sort:</label>
                        <input
                            wire:model="pageData.sort"
                            id="sort"
                            type="number"
                            min="0"
                            step="1"
                            class="w-16 rounded-md border border-zinc-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-accent focus:border-transparent dark:bg-zinc-800 dark:border-zinc-600 dark:text-white"
                        />
                    </div>
                </div>
            </div>
        @endif

        <x-noerd::tab-content :layout="$pageLayout" :showBlock="$this->hasPageFeatures">
            <x-slot:tab1>
                @if($collectionLayout)
                    @include('noerd::components.detail.block', $collectionLayout)
                @endif

                {{-- Elements für Tab 1 --}}
                @if($this->pageModel?->id && $this->hasPageFeatures)

                    <div x-sort="$wire.elementSort($item, $position)">
                        @foreach($this->pageModel->elements as $loopIndex => $elementPage)
                            <div x-sort:item="{{$elementPage->id}}" wire:key="sort-item-{{$elementPage->id}}">
                                <livewire:element-page-detail
                                    wire:key="element-page-{{$elementPage->id}}"
                                    :modelId="$elementPage->id"
                                >
                                </livewire:element-page-detail>
                            </div>
                        @endforeach
                    </div>

                    <div class="mt-8 mb-8 flex">
                        <div class="mt-4 mx-auto">
                            <x-noerd::buttons.primary
                                wire:click="$dispatch('noerdModal', {component: 'element-picker-modal', arguments: { token: 'insert-end' }})">
                                {{ __('Add Element') }}
                            </x-noerd::buttons.primary>
                        </div>
                    </div>

                @endif
            </x-slot:tab1>
        </x-noerd::tab-content>
    </div>

    <x-slot:footer>
        <x-noerd::delete-save-bar :showDelete="isset($pageId)"/>
    </x-slot:footer>

</x-noerd::page>
