title: 'Leistung'
titleList: 'Leistungen'
key: 'SERVICES'
buttonList: 'Neue Leistung'
description: ''
hasPage: true
fields:
  - { name: model.name, label: Name, type: translatableText, colspan: 6 }
  - { name: image, label: Bild, type: image, colspan: 6 }
#  - { name: model.category, label: 'Kategorie', type: select, options: ['as', 'asd'], colspan: 6 }
