title: Service
titleList: Services
key: SERVICES
buttonList: New Service
description: ''
hasPage: true
fields:
  - name: detailData.name
    label: Name
    type: translatableText
    colspan: 6
  - name: image
    label: Image
    type: image
    colspan: 6
